include:
  - Misc:
    - Contest:
    #   - Makefile:
    #     - misc/Makefile
    # - 'How Did We Get Here?':
      - Macros and debug:
        # - misc/speed/macros.tex
        - misc/speed/macros.hpp
        - misc/debug-list.md
  - Data Structures:
    - GNU PBDS:
      - ds/pbds.hpp
    - 2D Partial Sums:
      - ds/partial-sums-2D.hpp
    - Sparse Table:
      - ds/sparse-table.hpp
    - Fenwick Tree:
      - ds/fwt.hpp
    - Longest Increasing Subsequence:
      - misc/lis.hpp
    - Xobriest:
      - ds/xobriest.hpp
    # - Segment Tree (ZKW):
    #   - ds/segtree.hpp
    # - Line Container:
    #   - ds/line-container.hpp
    # - Li-Chao Tree:
    #   - ds/li-chao.hpp
    # - Heavy-Light Decomposition:
    #   - ds/hld.hpp
    # - Wavelet Matrix:
    #   - ds/wavelet-matrix.hpp
    # - Link-Cut Tree:
    #   - ds/lct.hpp
  - Graph:
    - Kuhn-Munkres algorithm:
      - graph/flows/km.hpp
    # - Shortest Path Faster Algorithm:
    #   - graph/spfa.hpp
    - Strongly Connected Components:
      - graph/scc.hpp
    - Biconnected Components:
      - Articulation Points:
        - graph/tarjan-ap.hpp
      # - Bridges:
      #   - graph/tarjan-b.hpp
    # - Centroid Decomposition:
    #   - graph/centroid-decomposition.hpp
  - Math:
    - SOS DP:
      - math/sosDP.hpp
    - Matrix:
      - math/matrix.hpp
    - Number Theory:
      - Mod Struct:
        - math/number-theory/modular.tex
        - math/number-theory/modular.hpp
      - Miller-Rabin:
        - math/number-theory/miller-rabin.hpp
      - Linear Sieve:
        - math/number-theory/sieve.hpp
      - Get Factors:
        - math/number-theory/all-factors.hpp
      - Extended GCD:
        - math/number-theory/extgcd.hpp
      - Chinese Remainder Theorem:
        - math/number-theory/crt.hpp
      - Pollard Rho:
        - math/number-theory/pollard-rho.hpp
      - De Brujin Sequence:
        - math/combinatorics/de-brujin.hpp
      - Combinatorics:
        - math/combinatorics/krishnaPnC.hpp
      # - Multinomial:
      #   - math/combinatorics/multinomial.hpp
  # - Numeric:
    # - Barrett Reduction:
    #   - numeric/barrett-reduction.hpp
      # - Long Long Multiplication:
      #   - numeric/ll-mul.hpp
    # - Fast Fourier Transform:
    #   - numeric/fft.hpp
    #   - numeric/fft-usage.hpp
    # - Fast Walsh-Hadamard Transform:
    #   - numeric/fwht.hpp
    # - Subset Convolution:
    #   - numeric/subset-convolution.hpp
    # - Linear Recurrences:
    #   - Berlekamp-Massey Algorithm:
    #     - numeric/berlekamp-massey.hpp
    #   - Linear Recurrence Calculation:
    #     - numeric/linear-recurrence.hpp
    # - Matrices:
    #   - Determinant:
    #     - numeric/det-mod.hpp
    #     - numeric/det-double.hpp
    #   - Inverse:
    #     - numeric/inverse.hpp
    #   - Characteristic Polynomial:
    #     - numeric/char-poly.hpp
    #   - Solve Linear Equation:
    #     - numeric/linear-eq.hpp
    # - Polynomial Interpolation:
    #   - numeric/interpolation.hpp
    # - Simplex Algorithm:
    #   - numeric/simplex.hpp
  - Geometry:
    - convex hull:
      - geometry/krishna-convex.hpp
    # - Point:
    #   - geometry/point.hpp
    #   - Quarternion:
    #     - geometry/quaternion.hpp
    #   - Spherical Coordinates:
    #     - geometry/spherical.hpp
    # - Segments:
    #   - geometry/segments.hpp
    # - Convex Hull:
    #   - geometry/convex-hull.hpp
    #   - 3D Hull:
    #     - geometry/3d-hull.hpp
    # - Angular Sort:
    #   - geometry/angular-sort.hpp
    # - Convex Polygon Minkowski Sum:
    #   - geometry/minkowski-sum.hpp
    # - Point In Polygon:
    #   - geometry/point-inclusion.hpp
    #   - Convex Version:
    #     - geometry/convex-inclusion.hpp
    #   - Offline Multiple Points Version:
    #     - geometry/multi-inclusion.hpp
    # - Closest Pair:
    #   - geometry/closest-pair.hpp
    # - Minimum Enclosing Circle:
    #   - geometry/min-enclosing-circle.hpp
    # - Delaunay Triangulation:
    #   - geometry/delaunay.hpp
    #   - Slower Version:
    #     - geometry/delaunay-slow.hpp
    # - Half Plane Intersection:
    #   - geometry/half-plane-intersection.hpp
  - Strings:
    - Knuth-Morris-Pratt Algorithm:
      - strings/kmp.hpp
    # - Suffix Array:
    #   - strings/suffix-array.hpp
    # - Suffix Tree:
    #   - strings/suffix-tree.hpp
    # - Cocke-Younger-Kasami Algorithm:
    #   - strings/cyk.hpp
    - Z Value:
      - strings/z-value.hpp
    - Manachers Algorithm:
      - strings/manacher.hpp
    # - Minimum Rotation:
    #   - strings/min-rotation.hpp
    # - column_break: true
    - Trie:
      - strings/trie.hpp
    - Aho-Corasick Automaton:
      - strings/ahocorasick.hpp
    # - Palindromic Tree:
    #   - strings/palindromic-tree.hpp
  # - Debug List:

dependencies:
  show: true
  ignore_cycles: false
